repos:


repos:
  - repo: local
    hooks:
    -   id: commitlint
        name: commitlint
        entry: ./commitlint.sh
        language: script
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
