version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - venv:/app/.venv
      - node-modules:/app/node_modules
    environment:
      MONGO_URI: mongodb://mongodb:27017/test
      SERVER_URL: http://server:3000
      LOG_LEVEL: DEBUG
    command: sleep infinity
    restart: always
