name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    services:
      server:
        image: yujiosaka/cronyx-server:latest
        ports:
          - 3000:3000
        env:
          SERVER_PORT: "3000"
          TIMEZONE: UTC
          JOB_STORE_SOURCE: mongodb
          JOB_STORE_URL: mongodb://mongodb:27017/test

      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          uv-version: 0.6.16

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
          bun install

      - name: Lint
        run: |
          uv run ruff check --output-format=github cronyx_client

      - name: Check code formatting
        run: |
          uv run ruff format --check cronyx_client

      - name: Run Pytype
        run: |
          uv run pytype cronyx_client

      - name: Run unit tests
        run: |
          uv run pytest
        env:
          SERVER_URL: http://127.0.0.1:3000
          MONGO_URI: mongodb://127.0.0.1:27017/test

      - id: semantic-release
        name: Run semantic-release
        run: |
          bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: |
          uv pip install build
          uv run python -m build
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Publish package
        run: |
          uv pip install twine
          uv run twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
        if: ${{ steps.semantic-release.outputs.nextVer != null }}
